# ~/.config/starship.toml

format = """
[](bg:#1C2B3A fg:#7AACD7)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

# Other symbols you might like: ğŸ‘½ ğŸ›¸ ğŸŒ  ğŸª ğŸŒŒ ğŸš€
[character]
success_symbol = "[ğŸ‘¾ ](green)"
error_symbol = "[ğŸ‘¾ ](red)"
vimcmd_symbol = "[ğŸ‘¾ ](yellow)"

[directory]
style = "bg:#1C2B3A fg:#7AACD7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[cmd_duration]
min_time = 500
format = "[ç¾½$duration](bold yellow)"

[git_branch]
symbol = "ğŸŒŒ "
format = "[$symbol$branch]($style)"
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "cyan"
conflicted = "ğŸ›¸"
ahead = "ğŸš€Ã—${count}"
behind = "ğŸ‘£Ã—${count}"
diverged = "â™ŠÃ—${ahead_count}Ã—${behind_count}"
untracked = "ğŸ›°ï¸Ã—${count}"
stashed = "ğŸ“¦"
modified = "ğŸ”§Ã—${count}"
staged = "ğŸ”­Ã—${count}"
renamed = "ğŸ“›Ã—${count}"
deleted = "ğŸŒ Ã—${count}"

[username]
style_user = "bg:#1C2B3A fg:#7AACD7"
style_root = "bg:#1C2B3A fg:#FF5555"
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold red)"
disabled = false

# Language versions
[python]
symbol = "ğŸ "
format = '[${symbol}${version} ]($style)'

[rust]
symbol = "ğŸ¦€ "
format = '[${symbol}${version} ]($style)'

[java]
symbol = "â˜• "
format = '[${symbol}${version} ]($style)'

[nodejs]
symbol = "ğŸŸ¢ "
format = '[${symbol}${version} ]($style)'

# Disable unused modules
[package]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[memory_usage]
disabled = true